import type { IconType } from "react-icons";
import {
  LuArrowLeft,
  LuBell,
  LuBuilding2,
  LuCalculator,
  LuCheck,
  LuChevronDown,
  LuChevronRight,
  LuCircleAlert,
  LuCircleCheck,
  LuClipboardList,
  LuCloudUpload,
  LuCopy,
  LuDownload,
  LuEllipsisVertical,
  LuEye,
  LuEyeOff,
  LuFile,
  LuFileText,
  LuFileUp,
  LuFilter,
  LuFolder,
  LuFolderInput,
  LuFolderPlus,
  LuGhost,
  LuHardDrive,
  LuHouse,
  LuImageOff,
  LuImages,
  LuInfo,
  LuLayers,
  LuLink,
  LuLock,
  LuLogOut,
  LuMenu,
  LuMessageSquare,
  LuPackage,
  LuPanelLeftClose,
  LuPanelLeftOpen,
  LuPencilLine,
  LuPlus,
  LuRuler,
  LuSearch,
  LuSend,
  LuSettings2,
  LuShare2,
  LuTrash2,
  LuTriangleAlert,
  LuUndo2,
  LuUpload,
  LuUser,
  LuX,
} from "react-icons/lu";

// Mapa nome → ícone Lucide (react-icons), preservando os nomes usados pelo
// protótipo (shared-components.jsx) para facilitar o porte das telas.
const ICON_MAP = {
  back: LuArrowLeft,
  bell: LuBell,
  box: LuPackage,
  building: LuBuilding2,
  calculator: LuCalculator,
  chat: LuMessageSquare,
  check: LuCheck,
  check_circle: LuCircleCheck,
  chevD: LuChevronDown,
  chevR: LuChevronRight,
  clipboard: LuClipboardList,
  close: LuX,
  cloud_upload: LuCloudUpload,
  copy: LuCopy,
  download: LuDownload,
  edit: LuPencilLine,
  error_circle: LuCircleAlert,
  eye: LuEye,
  eye_off: LuEyeOff,
  file: LuFile,
  file_pdf: LuFileText,
  file_up: LuFileUp,
  filter: LuFilter,
  folder: LuFolder,
  folder_plus: LuFolderPlus,
  ghost: LuGhost,
  home: LuHouse,
  image_off: LuImageOff,
  info: LuInfo,
  layers: LuLayers,
  library: LuImages,
  link: LuLink,
  lock: LuLock,
  logout: LuLogOut,
  menu: LuMenu,
  more_vert: LuEllipsisVertical,
  move: LuFolderInput,
  panel_close: LuPanelLeftClose,
  panel_open: LuPanelLeftOpen,
  person: LuUser,
  plus: LuPlus,
  ruler: LuRuler,
  search: LuSearch,
  send: LuSend,
  share: LuShare2,
  storage: LuHardDrive,
  trash: LuTrash2,
  tune: LuSettings2,
  undo: LuUndo2,
  upload: LuUpload,
  warning: LuTriangleAlert,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICON_MAP;

export const ICON_NAMES = Object.keys(ICON_MAP) as IconName[];

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
}

/** Ícone único por nome (linha Lu* do Lucide). Cor via `className` (text-*). */
export function Icon({ name, size = 16, className }: IconProps) {
  const Cmp = ICON_MAP[name];
  return <Cmp size={size} className={className} aria-hidden />;
}
